### ISSUE TITLE
Designing project structure

### ISSUE THREAD

**Issue by Navid-Ebadi-2003** [skeletknight/FINAL_AP_PROJECT_YOUTUBE#1]
Designing project structure and patterns around classes, 
attributes, methods and communication between them.
The structure and shape of the UI and how to create it
Database structure , tables , columns and how to communicate .
API and request - response structure for server and client

**Comment by A-Ghoreishi** [comment]
assignment received

**Comment by A-Ghoreishi** [comment]
phase 1 done
[Uploading Notes_240612_001544.pdf…]()
